(function () {
  const memoryGame = window.Playlab?.games?.memory?.createMemoryGame;
  const shapeSprintGame = window.Playlab?.games?.shapeSprint?.createShapeSprintGame;
  const colorPopGame = window.Playlab?.games?.colorPop?.createColorPopGame;
  const tapRabbitGame = window.Playlab?.games?.tapRabbit?.createTapRabbitGame;
  const findOddGame = window.Playlab?.games?.findOdd?.createFindOddGame;
  const shadowMatchGame = window.Playlab?.games?.shadowMatch?.createShadowMatchGame;
  const countStarsGame = window.Playlab?.games?.countStars?.createCountStarsGame;
  const pathFinderGame = window.Playlab?.games?.pathFinder?.createPathFinderGame;
  const fillTheDrinkGame = window.Playlab?.games?.fillTheDrink?.createFillTheDrinkGame;
  const suggestedGames = window.Playlab?.games?.suggested || {};

  const gameRegistry = [
    {
      id: "memory-match",
      name: "Memory Match",
      tagline: "Flip & find pairs",
      description: "Flip tiles, find matching pairs, and level up as you go.",
      icon: "🧠",
      tags: ["Ages 4+", "Memory"],
      status: "New",
      theme: { from: "#7c5cff", to: "#ff6fb5" },
      launch: memoryGame,
    },
    {
      id: "shape-sprint",
      name: "Shape Sprint",
      tagline: "Tap the right shape",
      description: "Find and tap the target shape before time runs out.",
      icon: "🔺",
      tags: ["Ages 5+", "Reflex"],
      status: "New",
      theme: { from: "#3ecfc0", to: "#7c5cff" },
      launch: shapeSprintGame,
    },
    {
      id: "color-pop",
      name: "Color Pop",
      tagline: "Pop the matching colors",
      description: "Tap the target color quickly before time runs out.",
      icon: "🎨",
      tags: ["Ages 4+", "Focus"],
      status: "New",
      theme: { from: "#ffb54c", to: "#ff6fb5" },
      launch: colorPopGame,
    },
    {
      id: "tap-rabbit",
      name: "Catch the Rabbit",
      tagline: "Peek-a-boo bunny time",
      description: "Silly bunnies pop from the burrows—catch them before they hide! Level up and grow your score.",
      icon: "🐰",
      tags: ["Ages 4+", "Speed"],
      status: "New",
      theme: { from: "#4ad18a", to: "#7c5cff" },
      launch: tapRabbitGame,
    },
    {
      id: "find-odd",
      name: "Find the Odd One",
      tagline: "Spot the unpaired one",
      description: "Many pairs appear, but one item has no pair. Find it fast!",
      icon: "🧩",
      tags: ["Ages 5+", "Focus"],
      status: "New",
      theme: { from: "#3ecfc0", to: "#ffb54c" },
      launch: findOddGame,
    },
    {
      id: "shadow-match",
      name: "Shadow Match",
      tagline: "Match the silhouette",
      description: "See a colourful picture, then tap its matching shadow. Can you tell shapes apart?",
      icon: "🌑",
      tags: ["Ages 4+", "Focus"],
      status: "New",
      theme: { from: "#7c5cff", to: "#3ecfc0" },
      launch: shadowMatchGame,
    },
    {
      id: "count-stars",
      name: "Count the Stars",
      tagline: "Count and pick the number",
      description: "Count all the items on screen and pick the right number before time runs out!",
      icon: "⭐",
      tags: ["Ages 4+", "Numbers"],
      status: "New",
      theme: { from: "#ffb54c", to: "#4ad18a" },
      launch: countStarsGame,
    },
    {
      id: "path-finder",
      name: "Path Finder",
      tagline: "Guide bunny to carrot",
      description: "Help the bunny reach the carrot by tapping the correct next tile.",
      icon: "🥕",
      tags: ["Ages 5+", "Strategy"],
      status: "New",
      theme: { from: "#4ad18a", to: "#ffb54c" },
      launch: pathFinderGame,
    },
    {
      id: "fill-the-drink",
      name: "Fill the Drink",
      tagline: "Pour to the perfect line",
      description: "Hold to pour each order. Stop in the green zone — too little or spilling the cup scores nothing.",
      icon: "🥤",
      tags: ["Ages 5+", "Timing"],
      status: "New",
      theme: { from: "#ff8c6b", to: "#7c5cff" },
      launch: fillTheDrinkGame,
    },
    {
      id: "word-whiz",
      name: "Word Whiz",
      tagline: "Tiny word puzzles",
      description: "Playful word puzzles for growing readers. Coming soon.",
      icon: "🔤",
      tags: ["Ages 6+", "Words"],
      status: "Coming Soon",
      theme: { from: "#4ad18a", to: "#3ecfc0" },
      comingSoon: true,
    },
    {
      id: "pattern-parade",
      name: "Pattern Parade",
      tagline: "Finish the sequence",
      description: "Spot the pattern and choose what comes next with shapes, colors, and silly icons.",
      icon: "🔁",
      tags: ["Ages 5+", "Logic"],
      status: "Suggested",
      theme: { from: "#ff6fb5", to: "#ffb54c" },
      hiddenOnLanding: true,
      launch: suggestedGames.createPatternParadeGame,
    },
    {
      id: "number-train",
      name: "Number Train",
      tagline: "Order the numbers",
      description: "Drag train cars into the right number order and help the little train roll away.",
      icon: "🚂",
      tags: ["Ages 4+", "Numbers"],
      status: "Suggested",
      theme: { from: "#3ecfc0", to: "#5f8bff" },
      landingPriority: -1,
      launch: suggestedGames.createNumberTrainGame,
    },
    {
      id: "bubble-letters",
      name: "Bubble Letters",
      tagline: "Pop the right letter",
      description: "Hear or see a letter, then pop the matching bubble before it floats away.",
      icon: "🔤",
      tags: ["Ages 4+", "Letters"],
      status: "Suggested",
      theme: { from: "#7c5cff", to: "#3ecfc0" },
      hiddenOnLanding: true,
      launch: suggestedGames.createBubbleLettersGame,
    },
    {
      id: "tiny-builder",
      name: "Tiny Builder",
      tagline: "Stack and balance",
      description: "Stack blocks, match outlines, and build cheerful little towers without tipping them.",
      icon: "🧱",
      tags: ["Ages 5+", "Balance"],
      status: "Suggested",
      theme: { from: "#ff8c6b", to: "#ffb54c" },
      hiddenOnLanding: true,
      launch: suggestedGames.createTinyBuilderGame,
    },
    {
      id: "music-maker",
      name: "Music Maker",
      tagline: "Copy the tune",
      description: "Listen to short musical patterns and tap the notes back in the same order.",
      icon: "🎵",
      tags: ["Ages 4+", "Memory"],
      status: "Suggested",
      theme: { from: "#4ad18a", to: "#7c5cff" },
      hiddenOnLanding: true,
      launch: suggestedGames.createMusicMakerGame,
    },
    {
      id: "sorting-shelf",
      name: "Sorting Shelf",
      tagline: "Group matching things",
      description: "Sort toys, foods, shapes, and colors onto the right shelves.",
      icon: "🧺",
      tags: ["Ages 4+", "Sorting"],
      status: "Suggested",
      theme: { from: "#ffb54c", to: "#4ad18a" },
      hiddenOnLanding: true,
      launch: suggestedGames.createSortingShelfGame,
    },
  ];

  window.Playlab = window.Playlab || {};
  window.Playlab.registry = gameRegistry;
})();
